<a href="https://colab.research.google.com/github/iestleija/4808-Programacion/blob/Unidad2/Unidad2/Practices/Practica18_266229.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Maestría en Inteligencia Artificial y Analítica de Datos**

- Curso: Programación para Analítica Descriptiva y Predictiva

- Semestre: Enero-Junio

- Profesor: Dr. Vicente García Jiménez
- Práctica: Práctica #18: Datos Temporales
- Alumno: Ismael Estrada Leija
- Matrícula: 266229

#Práctica #18: Datos Temporales
El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos categóricos.

In [107]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [108]:
# Importación de bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def print_bold(msg):
    print("\n\033[1m" + msg + "\033[0m")
file_path = '/content/drive/MyDrive/4808-programacion/U02/P18/Airdata.csv';

###Instrucciones:

- Descarga el archivo airdata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
- Crea un notebook en colab y guarda el archivo csv  en tu drive.
- Agrega secciones en el colab poniendo como título el nombre de cada ejercicio
- Sube un archivo txt que contenga la liga a tu notebook

# Ejercicio 01:Tipo de Datos Correcto

- Carga el conjunto de datos airdata.csv y verifica que cada columna tenga el tipo de datos correcto
- Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.
- Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto
- Imprime las primeras tres líneas

In [116]:
# normal file data load
df = pd.read_csv(file_path)
df.head(3)

print_bold('displaying data types')
print(df.dtypes)

# forcing the datatype for datetime column
air_df = pd.read_csv(file_path, parse_dates=['DateTime'])

print_bold('display data types with datetime data type forced')
print(air_df.dtypes)

print_bold('data sample with the fixed data type')
air_df.head(3)

displaying data types
DateTime           object
Temperature       float64
Humidity            int64
Wind_Speed        float64
Wind_Direction    float64
NO2_Location_A    float64
NO2_Location_B    float64
NO2_Location_C    float64
dtype: object

display data types with datetime data type forced
DateTime          datetime64[ns]
Temperature              float64
Humidity                   int64
Wind_Speed               float64
Wind_Direction           float64
NO2_Location_A           float64
NO2_Location_B           float64
NO2_Location_C           float64
dtype: object

data sample with the fixed data type

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2,87,1,76,39,53,62
1,2020-01-01 01:00:00,1,89,3,113,38,45,53
2,2020-01-01 02:00:00,2,85,4,135,NaN,48,55

In [110]:
#correccion


# Ejercicio 02: Extraer componentes de fecha y tiempo

- De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes
- Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

In [111]:
# reload dataframe to make this exercise independent
air_df = pd.read_csv(file_path, parse_dates=['DateTime'])

# creating detailed date time columns
air_df['year'] = air_df['DateTime'].dt.year
air_df['month'] = air_df['DateTime'].dt.month
air_df['day'] = air_df['DateTime'].dt.day
air_df['hour'] = air_df['DateTime'].dt.hour

print_bold('data sample with detailed date time columns')
air_df.head(3)

data sample with detailed date time columns

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,year,month,day,hour
0,2020-01-01 00:00:00,2,87,1,76,39,53,62,2020,1,1,0
1,2020-01-01 01:00:00,1,89,3,113,38,45,53,2020,1,1,1
2,2020-01-01 02:00:00,2,85,4,135,NaN,48,55,2020,1,1,2

# Ejercicio 03: Aritmética - Suma de Intervalos (timedelta)

- Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'. Guarda el resultado en una nueva columna y agrega al dataframe.
- Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

In [112]:

# reload dataframe to make this exercise independent
air_df = pd.read_csv(file_path, parse_dates=['DateTime'])

air_df['next_datetime'] = air_df['DateTime'] + pd.Timedelta(days=10, hours=7, minutes=15)

print_bold('data sample with next datetime column')
print()
air_df[['DateTime','next_datetime']].head(3)

data sample with next datetime column

             DateTime       next_datetime
0 2020-01-01 00:00:00 2020-01-11 07:15:00
1 2020-01-01 01:00:00 2020-01-11 08:15:00
2 2020-01-01 02:00:00 2020-01-11 09:15:00

# Ejercicio 04: Timestamp

- Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix. Guarda el resultado en una nueva columna
- Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix
---
Se realiza la conversión desde datetime a unix timestamp como fue solicitado

In [114]:
pd.options.display.float_format = '{:.0f}'.format
# reload dataframe to make this exercise independent
air_df = pd.read_csv(file_path, parse_dates=['DateTime'])

# Four common timestamps obtained from DateTime column
air_df['unix_timestamp'] = (air_df['DateTime'].apply(lambda x: x.timestamp()))  # this alternative returns the timestamp in float64

print_bold('Displaying DateTime and unix timestamp')

air_df.style.format("{:.0f}")
air_df[['DateTime','unix_timestamp']].head(3)
#air_df.dtypes

Displaying DateTime and unix timestamp

             DateTime  unix_timestamp
0 2020-01-01 00:00:00      1577836800
1 2020-01-01 01:00:00      1577840400
2 2020-01-01 02:00:00      1577844000

In [117]:
### this cell is for reference only with more timestamp conversions ###
# air_df['unix_ts_in_secs'] = (air_df['DateTime'].apply(lambda x: x.timestamp()))  # this alternative returns the timestamp in float64
# air_df['unix_ts_in_secs'] =(air_df['DateTime'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s') # this is similar to the academic video

# air_df['web_js_ts_in_ms'] =(air_df['DateTime'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1ms') # commonly used in web dev or js

# # The following two timestamps are used in real time systems and high precision applications
# air_df['ts_in_micro_sec'] =(air_df['DateTime'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1us')
# air_df['ts_in_nano_sec'] =(air_df['DateTime'] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1ns')

# Ejercicio 05: Filtrado de Fechas

- Utiliza la columna 'DateTime' y Filtra aquellas fechas que son mayores a 2020-11-01
- Imprime el resultado

In [115]:
# reload dataframe to make this exercise independent
air_df = pd.read_csv(file_path, parse_dates=['DateTime'])

#filtered as required
air_df_filtrado = air_df[air_df['DateTime'] > '2020-11-01']
air_df_filtrado

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
7321,2020-11-01 01:00:00,14,58,7,131,18,24,44
7322,2020-11-01 02:00:00,14,40,7,158,13,19,36
7323,2020-11-01 03:00:00,13,43,8,165,12,14,30
7324,2020-11-01 04:00:00,12,51,8,155,10,14,31
7325,2020-11-01 05:00:00,13,59,8,149,10,14,33
...,...,...,...,...,...,...,...,...
8779,2020-12-31 19:00:00,5,72,5,252,53,33,67
8780,2020-12-31 20:00:00,5,74,3,186,50,34,67
8781,2020-12-31 21:00:00,4,84,11,252,43,26,59
8782,2020-12-31 22:00:00,4,88,8,220,40,20,44
8783,2020-12-31 23:00:00,3,89,7,212,39,30,47

#Conclusión
Usando las librerías de Python y el objeto de acceso `pandas.Series.dt` para manejo de datos temporales se completó la presente práctica. (Pandas team, 2026)

#Referencias
Pandas team. (2026). pandas documentation—Pandas 3.0.0 documentation. https://pandas.pydata.org/docs/index.html